=== raquelmvz/EjerciciosFinalesDTD/EJERCICIO 20-21/motorsol.dtd
<!ELEMENT motorsol (motores, piezas, secciones, empleados)>
<!ELEMENT piezas (pieza+)>
<!ELEMENT pieza EMPTY>
<!ATTLIST pieza 
	id ID #REQUIRED 
	compuesta IDREFS #IMPLIED>
<!ELEMENT motores (motor+)>
<!ELEMENT motor (trabajador+)>
<!ATTLIST motor 
	id ID #REQUIRED
	responsable IDREF #REQUIRED
	piezas IDREFS #REQUIRED>
<!ELEMENT trabajador EMPTY>
<!ATTLIST trabajador
	cod IDREF #REQUIRED
	familiares IDREFS #IMPLIED>
 <!ELEMENT secciones (seccion+)>
 <!ELEMENT seccion (realiza+)>
 <!ELEMENT realiza EMPTY>
 <!ATTLIST seccion cod ID #REQUIRED>
 <!ATTLIST realiza motor IDREF #REQUIRED>
<!ELEMENT empleados (empleado+)>
<!ELEMENT empleado EMPTY>
<!ATTLIST empleado nif ID #REQUIRED>

=== raquelmvz/EjerciciosFinalesDTD/EJERCICIO 20-21/motorsol.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE motorsol SYSTEM "motorsol.dtd">

<motorsol>

	<motores>
		<motor id="m1" responsable="_27111111F" piezas="p1 p4">
			<trabajador cod="_27111111F"/>
			<trabajador cod="_27111112F" familiares="_27111113F _27111114F"/>
		</motor>

		<motor id="m2" responsable="_27111112F" piezas="p3">
			<trabajador cod="_27111111F"/>
			<trabajador cod="_27111112F" familiares="_27111113F"/>
		</motor>

		<motor id="m3" responsable="_27111114F" piezas="p2">
			<trabajador cod="_27111114F"/>
			<trabajador cod="_27111115F" familiares="_27111116F"/>
		</motor>
	</motores>

	<piezas>
		<pieza id="p1" compuesta="p2 p3"/> <!-- esto son referencias-->
		<pieza id="p2"/>
		<pieza id="p3"/>
		<pieza id="p4"/>
	</piezas>

	<secciones>
		<seccion cod="s1">
			<realiza motor="m1"/>
			<realiza motor="m2"/>
		</seccion>

		<seccion cod="s2">
			<realiza motor="m3"/>
		</seccion>
	</secciones>

	<empleados>
		<empleado nif="_27111111F"/>
		<empleado nif="_27111112F"/>
		<empleado nif="_27111113F"/>
		<empleado nif="_27111114F"/>
		<empleado nif="_27111115F"/>
		<empleado nif="_27111116F"/>
	</empleados>

</motorsol>
